apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: hackergarten
  labels:
    app: nginx
spec:
  replicas: 30
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: http2-nginx
          image: nginx:1.7.9
          ports:
            - containerPort: 80
